services:

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: prestamosdb
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Chn.2026"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
    volumes:
      - sqlserver_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P \"Chn.2026\" -C -Q 'SELECT 1' || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  db-init:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: prestamoschn-db-init
    depends_on:
      sqlserver:
        condition: service_healthy
    command: >
      /opt/mssql-tools18/bin/sqlcmd -S sqlserver -U sa -P "Chn.2026" -C
        -Q "IF DB_ID('prestamosdb') IS NULL CREATE DATABASE prestamosdb"

  backend:
    image: marliton21/prestamos-backend:1.0
    container_name: backend
    depends_on:
      db-init:
        condition: service_completed_successfully
    environment:
      DB_URL: "jdbc:sqlserver://sqlserver:1433;databaseName=prestamosdb;encrypt=false;trustServerCertificate=true"
      DB_USER: "sa"
      DB_PASSWORD: "Chn.2026"
      CORS_ORIGIN: "http://localhost:4200"
    ports:
      - "8080:8080"

  frontend:
    image: marliton21/prestamos-frontend:1.0
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "4200:80"

volumes:
  sqlserver_data: